language: java
jdk:
  - openjdk8
  - openjdk11
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
script:
  - ./mvnw verify -B
  - ./mvnw site -pl docs -B -q
after_success:
  - bash ci/after_success.sh
cache:
  directories:
    - $HOME/.m2
deploy:
  - provider: script
    script: bash ci/deploy-snapshot.sh
    on:
      repo: dropwizard/dropwizard
      branch: master
      jdk: openjdk8
  - provider: script
    script: bash ci/deploy-release.sh
    on:
      repo: dropwizard/dropwizard
      tags: true
      jdk: openjdk8
# encrypted CI_DEPLOY_USERNAME and CI_DEPLOY_PASSWORD
# values for maven deploy. these have been encrypted
# with the public key from https://github.com/dropwizard/dropwizard
# and won't work in any other repository. if you want
# to run CI in your local fork you'll need to run `travis encrypt ...`
# accordingly (http://docs.travis-ci.com/user/encryption-keys/)
env:
  global:
    - secure: "N3xMOoDt6RyjUma4DRU8h8FjsXT4HJQmlJmJqW+MdpVCFxB11+nblZO20hWIHFy8o4JXsfiXB4ThMNbevjNIsjK2+kDII6cMRXefnDyzZZLf4Tu4460UaPAhVqQ+gXyWDy8PauakwKxqYQOogh+UfawGdXXUIz+ab98OX8tZO3w="
    - secure: "WY1zEZD8nwGQXaYDrItkBWmYHhbQ3Ekseq82cTIJedG7zb8KbwpVDUo+6yRf1EPmpnDbRE9N0wgtzQq8B3+X87ZnO6RrEuv6ulkLJJlrwcRmRjfDY9rwRTUUbFZYrHP0fiLedPE6xpokPiO7Y+tRpofVfv2YnxW69GWwQG224KY="
    - secure: "W4rGYMaNKW2K1oSJFEr1Q+InQxvW4cdXk6Z1wE+U3CeZd8YeZ8RaaRUVObTMeeUvIzYlbU/stb9dghQMyYKjgaOZE3zWzDV9NP1e83sX7LyCd3q9wufEzI2dwenfXDnVHehG110wXWjUQSAwYyUTXn5bzMvyHSCqwN4X5mGSFzw="
    - JAVA_OPTS: "'-Xms512m -Xmx2g'"
